#!/usr/bin/env python3
# Import stubs for the final link: one shared object per library the anchor
# binary needs, exporting exactly the symbols, versions, types, bindings and
# sizes the anchor imports (ld copies sizes into .dynsym and sizes dynbss).
# usage: tools/implib.py ANCHOR imports   -> imports/<soname>.{S,map}
import os, re, subprocess, sys

anchor, out = sys.argv[1:3]
os.makedirs(out, exist_ok=True)
run = lambda *a: subprocess.run(a, capture_output=True, text=True, check=True).stdout

# version index -> library, from .gnu.version_r
lib, ver_lib = None, {}
for l in run('readelf', '-VW', anchor).splitlines():
    m = re.search(r'File: (\S+)', l)
    if m:
        lib = m[1]
    m = re.search(r'Name: (\S+)\s+Flags.*Version: (\d+)', l)
    if m and lib:
        ver_lib[int(m[2])] = lib
needed = re.findall(r'\(NEEDED\).*\[(\S+)\]', run('readelf', '-dW', anchor))

syms = {n: [] for n in needed}
for l in run('readelf', '--dyn-syms', '-W', anchor).splitlines():
    f = l.split()
    if len(f) < 8 or not f[0].rstrip(':').isdigit():
        continue
    size, typ, bind, ndx, name = int(f[2], 0), f[3], f[4], f[6], f[7]
    if '@' not in name:
        continue
    name, ver = name.split('@')
    syms[ver_lib[int(f[8].strip('()'))]].append((name, ver, typ, bind, size))

# Weak references the real libraries make (their own startfiles); the anchor's
# .dynstr records each at that library's turn, so the stubs make them too.
WEAKREF = {'libdl.so.2': ['__gmon_start__'], 'libstdc++.so.5': ['_Jv_RegisterClasses'],
           'libc.so.6': ['_IO_stdin_used']}

# glibc 2.1 gave these a new default version beside the 2.0 one, through .symver;
# the anchor's .dynstr orders them by their versioned names.
SYMVER = {'GLIBC_2.1'}

# ld walks each hash bucket newest first: define in reverse .dynstr order so
# names sharing a bucket come out in the anchor's order.
strs = run('readelf', '-p', '.dynstr', anchor)
rank = {m[1]: int(m[0], 16) for m in re.findall(r'\[\s*([0-9a-f]+)\]\s+(\S+)', strs)}

HDR = '/* Generated by tools/implib.py from the original binary\'s import table. */'

for so, lst in syms.items():
    lst.sort(key=lambda e: -rank.get(e[0], 0))
    asm = [HDR]
    for sec, kind in (('text', 'FUNC'), ('data', 'OBJECT')):
        asm.append('\t.' + sec)
        for name, ver, typ, bind, size in lst:
            if typ != kind:
                continue
            label = name
            if ver in SYMVER:
                label = '__new_' + name
                asm.append('\t.symver\t%s, %s@@%s' % (label, name, ver))
            asm += ['\t.p2align\t2'] if kind == 'OBJECT' else []
            asm += ['\t.%s\t%s' % ('weak' if bind == 'WEAK' else 'globl', label),
                    '\t.type\t%s,@%s' % (label, 'function' if kind == 'FUNC' else 'object'), '%s:' % label]
            asm += ['\t.skip\t%d' % size] if size else []
            asm += ['\t.size\t%s,%d' % (label, size)]
    for name in WEAKREF.get(so, []):
        asm += ['\t.weak\t%s' % name, '\t.long\t%s' % name]
    open(os.path.join(out, so + '.S'), 'w').write('\n'.join(asm) + '\n')
    vers = []
    for name, ver, *_ in lst:
        if ver not in vers:
            vers.append(ver)
    vs = [HDR]
    for i, v in enumerate(sorted(vers)):
        names = ''.join('\t\t%s;\n' % n for n, vv, *_ in lst if vv == v and v not in SYMVER)
        local = '\tlocal: *;\n' if i == 0 else ''
        vs.append('%s {\n%s%s};' % (v, '\tglobal:\n' + names if names else '', local))
    open(os.path.join(out, so + '.map'), 'w').write('\n'.join(vs) + '\n')
    print(so, len(lst), 'symbols', ' '.join(vers))
